---
services:
  openbao:
    image: ghcr.io/openbao/openbao:latest
    container_name: openbao
    command: server -config=/openbao/config/config.json
    restart: unless-stopped

    ports:
      - "8200:8200"

    environment:
      VAULT_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200

    cap_add:
      - IPC_LOCK

    volumes:
      - openbao-data:/openbao/file
      - ./config:/openbao/config


volumes:
  openbao-data:

